services:
  post-comments:
    build: ./
    command: ./wait.sh ozon-contest ./main
    ports:
      - "8080:8080"
    depends_on:
      - ozon-contest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=OzonContest

  ozon-contest:
    restart: always

    image: postgres:13.3
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=OzonContest


    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql