package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"
	"system-for-adding-and-reading-posts-and-comments/graph/model"
	"system-for-adding-and-reading-posts-and-comments/innternal/models"

	"github.com/google/uuid"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*model.Post, error) {

	post := &models.Post{
		Title:            input.Title,
		Body:             input.Body,
		UserId:           input.UserID,
		DisabledComments: input.DisabledComments,
	}
	post, err := r.Repository.PostRepository.CreatePost(ctx, post)
	if err != nil {
		return nil, err
	}
	postResult := &model.Post{
		PostID:           post.PostId,
		Title:            post.Title,
		Body:             post.Body,
		UserID:           post.UserId,
		DisabledComments: post.DisabledComments,
	}

	return postResult, err
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, input model.UpdatePost) (*model.Post, error) {
	post := &models.Post{
		Title:            input.Title,
		Body:             input.Body,
		UserId:           input.UserID,
		DisabledComments: input.DisabledComments,
	}
	post, err := r.Repository.PostRepository.UpdatePost(ctx, post)
	if err != nil {
		return nil, err
	}
	result := &model.Post{
		PostID:           post.PostId,
		Title:            post.Title,
		Body:             post.Body,
		UserID:           post.UserId,
		DisabledComments: post.DisabledComments,
	}
	return result, err
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, postID uuid.UUID) (bool, error) {
	err := r.Repository.PostRepository.DeletePostByID(ctx, postID)
	if err != nil {
		return false, err
	}
	return true, err
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.NewComment) (*model.Comment, error) {
	comment := &models.Comment{
		Body:   input.Body,
		UserId: input.UserID,
		Parent: *input.ParentID,
		Post:   input.PostID,
	}
	comment, err := r.Repository.CommentRepository.CreateComment(ctx, comment)
	if err != nil {
		return nil, err
	}
	commentResult := &model.Comment{
		Body:   comment.Body,
		UserID: comment.UserId,
		Parent: comment.Parent,
		Post:   comment.Post,
	}

	return commentResult, err
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, input *model.UpdateComment) (*model.Comment, error) {
	comment := &models.Comment{
		Body: input.Body,
	}
	comment, err := r.Repository.CommentRepository.UpdateComment(ctx, comment)
	if err != nil {
		return nil, err
	}
	result := &model.Comment{
		Body:   comment.Body,
		UserID: comment.UserId,
		Parent: comment.Parent,
		Post:   comment.Post,
	}
	return result, err
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, commentID uuid.UUID) (bool, error) {
	err := r.Repository.CommentRepository.DeleteCommentByID(ctx, commentID)
	if err != nil {
		return false, err
	}
	return true, err
}

// CreatUser is the resolver for the creatUser field.
func (r *mutationResolver) CreatUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	user := &models.User{
		Name: input.Name,
	}
	user, err := r.Repository.UserRepository.CreateUser(ctx, user)
	if err != nil {
		return nil, err
	}
	commentResult := &model.User{
		UserID: user.UserId,
		Name:   user.Name,
	}

	return commentResult, err
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, userID uuid.UUID) (bool, error) {
	err := r.Repository.UserRepository.DeleteUserByID(ctx, userID)
	if err != nil {
		return false, err
	}
	return true, err
}

// Post is the resolver for the Post field.
func (r *queryResolver) Post(ctx context.Context, postID uuid.UUID) (*model.Post, error) {
	return r.Repository.PostRepository.GetPostByID(ctx, postID)
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, limit *int, offset *int, postId uuid.UUID) ([]*model.Comment, error) {
	return r.Repository.CommentRepository.GetCommentsForPost(ctx, postId, *limit, *offset)
}

// NewComment is the resolver for the newComment field.
func (r *subscriptionResolver) NewComment(ctx context.Context, postID uuid.UUID) (<-chan *model.Comment, error) {
	panic(fmt.Errorf("not implemented: NewComment - newComment"))
}

type mutationResolver struct{ *Resolver }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) Posts(ctx context.Context, limit *int, offset *int) ([]*model.Post, error) {
	panic(fmt.Errorf("not implemented: Posts - Posts"))
}
